---
abstract: 'a flexible POE-based RADIUS client'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Client-RADIUS
no_index:
  directory:
    - xt
    - inc
    - t
    - examples
requires:
  Math::Random: 0.69
  Net::Radius::Dictionary: 1.55
  Net::Radius::Packet: 1.55
  POE: 0.9999
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
